@startuml "Защита храненимых данных"


artifact c #green as "
исходные данные
" 

artifact confidentialStored #green as "
конфиденциальные
хранимые данные
" 


artifact u #red as "
незащищённые данные
" 

component [DataBase] #red
component [DataProcessor] #green

[DataProcessor] -- c
[DataBase] -- confidentialStored
[DataBase] -- u

[DataBase] <-[#green] [DataProcessor]
[DataBase] -[#red]> [DataProcessor]

@enduml